services:
  - type: web
    name: sigrafilm-noc
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: APP_SECRET
        value: "cambia-questa-stringa-con-una-lunga-casuale"
